---
name: bakery

releases:
- name: bakery
  version: latest
- name: capi
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: bakery
  instances: 1
  azs: [ lab ]
  vm_type: small
  persistent_disk_type: 50GB
  stemcell: default
  networks:
  - name: vmnet
  jobs:
  - name: bakery
    release: bakery
  - name: ppi
    release: bakery
    properties:
      ppi:
        config: |
          {
            "piList": {
              "687680cd": {
                "piId": "687680cd",
                "id": 1,
                "url": "http://192.168.192.17"
              },
              "41f46c11": {
                "piId": "41f46c11",
                "id": 0,
                "url": "http://192.168.192.17"
              },
              "8d26580e": {
                "piId": "8d26580e",
                "id": 2,
                "url": "http://192.168.192.17"
              }
            }
          }

  - name: hooktftp
    release: bakery
  - name: dnsmasq
    release: bakery
  - name: debian_nfs_server
    release: capi
    properties:
      nfs_server:
        allow_from_entries:
          - 0.0.0.0

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
